import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import { usePrefix } from '../helpers/prefix';
import { getSpacingClassNames } from '../utilities/spacing';

function FlexBox(props) {
  const {
    as: Component,
    style,
    children,
    className,
    display,
    displaySm,
    displayMd,
    displayLg,
    displayXl,
    displayXxl,
    width,
    direction,
    directionSm,
    directionMd,
    directionLg,
    directionXl,
    directionXxl,
    justifyContent,
    justifyContentSm,
    justifyContentMd,
    justifyContentLg,
    justifyContentXl,
    justifyContentXxl,
    alignItems,
    alignItemsSm,
    alignItemsMd,
    alignItemsLg,
    alignItemsXl,
    alignItemsXxl,
    alignSelf,
    alignSelfSm,
    alignSelfMd,
    alignSelfLg,
    alignSelfXl,
    alignSelfXxl,
    isFill,
    isFillSm,
    isFillMd,
    isFillLg,
    isFillXl,
    isFillXxl,
    flexGrow,
    flexGrowSm,
    flexGrowMd,
    flexGrowLg,
    flexGrowXl,
    flexGrowXxl,
    flexShrink,
    flexShrinkSm,
    flexShrinkMd,
    flexShrinkLg,
    flexShrinkXl,
    flexShrinkXxl,
    isWrap,
    isWrapSm,
    isWrapMd,
    isWrapLg,
    isWrapXl,
    isWrapXxl,
    isNoWrap,
    isNoWrapSm,
    isNoWrapMd,
    isNoWrapLg,
    isNoWrapXl,
    isNoWrapXxl,
    isWrapReverse,
    isWrapReverseSm,
    isWrapReverseMd,
    isWrapReverseLg,
    isWrapReverseXl,
    isWrapReverseXxl,
    order,
    orderSm,
    orderMd,
    orderLg,
    orderXl,
    orderXxl,
    alignContent,
    alignContentSm,
    alignContentMd,
    alignContentLg,
    alignContentXl,
    alignContentXxl,
    margin,
    marginSm,
    marginMd,
    marginLg,
    marginXl,
    marginXxl,
    marginX,
    marginY,
    mt,
    me,
    mb,
    ms,
    padding,
    paddingSm,
    paddingMd,
    paddingLg,
    paddingXl,
    paddingXxl,
    paddingX,
    paddingY,
    pt,
    pe,
    pb,
    ps,
    bgColor,
    textColor,
    isBorder,
  } = props;

  const BASE_CLASS_NAME = usePrefix('d', display);

  const classes = classNames(
    BASE_CLASS_NAME,
    {
      [usePrefix('d-sm', displaySm)]: displaySm !== null,
      [usePrefix('d-md', displayMd)]: displayMd !== null,
      [usePrefix('d-lg', displayLg)]: displayLg !== null,
      [usePrefix('d-xl', displayXl)]: displayXl !== null,
      [usePrefix('d-xxl', displayXxl)]: displayXxl !== null,
      [usePrefix('w', width)]: width !== null,
      [usePrefix('flex', direction)]: direction,
      [usePrefix('flex-sm', directionSm)]: directionSm,
      [usePrefix('flex-md', directionMd)]: directionMd,
      [usePrefix('flex-lg', directionLg)]: directionLg,
      [usePrefix('flex-xl', directionXl)]: directionXl,
      [usePrefix('flex-xxl', directionXxl)]: directionXxl,
      [usePrefix('justify-content', justifyContent)]: justifyContent,
      [usePrefix('justify-content-sm', justifyContentSm)]: justifyContentSm,
      [usePrefix('justify-content-md', justifyContentMd)]: justifyContentMd,
      [usePrefix('justify-content-lg', justifyContentLg)]: justifyContentLg,
      [usePrefix('justify-content-xl', justifyContentXl)]: justifyContentXl,
      [usePrefix('justify-content-xxl', justifyContentXxl)]: justifyContentXxl,
      [usePrefix('align-items', alignItems)]: alignItems,
      [usePrefix('align-items-sm', alignItemsSm)]: alignItemsSm,
      [usePrefix('align-items-md', alignItemsMd)]: alignItemsMd,
      [usePrefix('align-items-lg', alignItemsLg)]: alignItemsLg,
      [usePrefix('align-items-xl', alignItemsXl)]: alignItemsXl,
      [usePrefix('align-items-xxl', alignItemsXxl)]: alignItemsXxl,
      [usePrefix('align-self', alignSelf)]: alignSelf,
      [usePrefix('align-self-sm', alignSelfSm)]: alignSelfSm,
      [usePrefix('align-self-md', alignSelfMd)]: alignSelfMd,
      [usePrefix('align-self-lg', alignSelfLg)]: alignSelfLg,
      [usePrefix('align-self-xl', alignSelfXl)]: alignSelfXl,
      [usePrefix('align-self-xxl', alignSelfXxl)]: alignSelfXxl,
      'flex-fill': isFill,
      'flex-sm-fill': isFillSm,
      'flex-md-fill': isFillMd,
      'flex-lg-fill': isFillLg,
      'flex-xl-fill': isFillXl,
      'flex-xxl-fill': isFillXxl,
      [usePrefix('flex-grow', flexGrow)]: flexGrow !== null,
      [usePrefix('flex-sm-grow', flexGrowSm)]: flexGrowSm !== null,
      [usePrefix('flex-md-grow', flexGrowMd)]: flexGrowMd !== null,
      [usePrefix('flex-lg-grow', flexGrowLg)]: flexGrowLg !== null,
      [usePrefix('flex-xl-grow', flexGrowXl)]: flexGrowXl !== null,
      [usePrefix('flex-xxl-grow', flexGrowXxl)]: flexGrowXxl !== null,
      [usePrefix('flex-shrink', flexShrink)]: flexShrink !== null,
      [usePrefix('flex-sm-shrink', flexShrinkSm)]: flexShrinkSm !== null,
      [usePrefix('flex-md-shrink', flexShrinkMd)]: flexShrinkMd !== null,
      [usePrefix('flex-lg-shrink', flexShrinkLg)]: flexShrinkLg !== null,
      [usePrefix('flex-xl-shrink', flexShrinkXl)]: flexShrinkXl !== null,
      [usePrefix('flex-xxl-shrink', flexShrinkXxl)]: flexShrinkXxl !== null,
      'flex-wrap': isWrap,
      'flex-sm-wrap': isWrapSm,
      'flex-md-wrap': isWrapMd,
      'flex-lg-wrap': isWrapLg,
      'flex-xl-wrap': isWrapXl,
      'flex-xxl-wrap': isWrapXxl,
      'flex-nowrap': isNoWrap,
      'flex-sm-nowrap': isNoWrapSm,
      'flex-md-nowrap': isNoWrapMd,
      'flex-lg-nowrap': isNoWrapLg,
      'flex-xl-nowrap': isNoWrapXl,
      'flex-xxl-nowrap': isNoWrapXxl,
      'flex-wrap-reverse': isWrapReverse,
      'flex-wrap-sm-reverse': isWrapReverseSm,
      'flex-wrap-md-reverse': isWrapReverseMd,
      'flex-wrap-lg-reverse': isWrapReverseLg,
      'flex-wrap-xl-reverse': isWrapReverseXl,
      'flex-wrap-xxl-reverse': isWrapReverseXxl,
      [usePrefix('order', order)]: order !== null,
      [usePrefix('order-sm', order)]: orderSm !== null,
      [usePrefix('order-md', order)]: orderMd !== null,
      [usePrefix('order-lg', order)]: orderLg !== null,
      [usePrefix('order-xl', order)]: orderXl !== null,
      [usePrefix('order-xxl', order)]: orderXxl !== null,
      [usePrefix('align-content', alignContent)]: alignContent,
      [usePrefix('align-content-sm', alignContentSm)]: alignContentSm,
      [usePrefix('align-content-md', alignContentMd)]: alignContentMd,
      [usePrefix('align-content-lg', alignContentLg)]: alignContentLg,
      [usePrefix('align-content-xl', alignContentXl)]: alignContentXl,
      [usePrefix('align-content-xxl', alignContentXxl)]: alignContentXxl,
      [getSpacingClassNames('m', margin)]: margin !== null,
      [getSpacingClassNames('m', marginSm, 'sm')]: marginSm !== null,
      [getSpacingClassNames('m', marginMd, 'md')]: marginMd !== null,
      [getSpacingClassNames('m', marginLg, 'lg')]: marginLg !== null,
      [getSpacingClassNames('m', marginXl, 'xl')]: marginXl !== null,
      [getSpacingClassNames('m', marginXxl, 'xxl')]: marginXxl !== null,
      [getSpacingClassNames('mx', marginX)]: marginX !== null,
      [getSpacingClassNames('my', marginY)]: marginY !== null,
      [usePrefix('mt', mt)]: mt !== null,
      [usePrefix('me', me)]: me !== null,
      [usePrefix('mb', mb)]: mb !== null,
      [usePrefix('ms', ms)]: ms !== null,
      [getSpacingClassNames('p', padding)]: padding !== null,
      [getSpacingClassNames('p', paddingSm, 'sm')]: paddingSm !== null,
      [getSpacingClassNames('p', paddingMd, 'Md')]: paddingMd !== null,
      [getSpacingClassNames('p', paddingLg, 'lg')]: paddingLg !== null,
      [getSpacingClassNames('p', paddingXl, 'xl')]: paddingXl !== null,
      [getSpacingClassNames('p', paddingXxl, 'xxl')]: paddingXxl !== null,
      [getSpacingClassNames('px', paddingX)]: paddingX !== null,
      [getSpacingClassNames('py', paddingY)]: paddingY !== null,
      [usePrefix('pt', pt)]: pt !== null,
      [usePrefix('pe', pe)]: pe !== null,
      [usePrefix('pb', pb)]: pb !== null,
      [usePrefix('ps', ps)]: ps !== null,
      [usePrefix('bg', bgColor)]: bgColor,
      [usePrefix('text', textColor)]: textColor,
      border: isBorder,
      [usePrefix('border', isBorder)]: typeof isBorder === 'string',
    },
    className,
  );

  return (
    <Component style={style} className={classes}>
      {children}
    </Component>
  );
}

FlexBox.propTypes = {
  as: PropTypes.oneOf([
    'div',
    'span',
  ]),
  style: PropTypes.shape({}),
  children: PropTypes.node.isRequired,
  className: PropTypes.oneOfType([
    PropTypes.object,
    PropTypes.string,
  ]),
  display: PropTypes.oneOf([
    'flex',
    'inline-flex',
  ]),
  displaySm: PropTypes.oneOf([
    'flex',
    'inline-flex',
  ]),
  displayMd: PropTypes.oneOf([
    'flex',
    'inline-flex',
  ]),
  displayLg: PropTypes.oneOf([
    'flex',
    'inline-flex',
  ]),
  displayXl: PropTypes.oneOf([
    'flex',
    'inline-flex',
  ]),
  displayXxl: PropTypes.oneOf([
    'flex',
    'inline-flex',
  ]),
  width: PropTypes.oneOf([0, 25, 50, 75, 100, 'auto']),
  direction: PropTypes.oneOf([
    'row',
    'row-reverse',
    'column',
    'column-reverse',
  ]),
  directionSm: PropTypes.oneOf([
    'row',
    'row-reverse',
    'column',
    'column-reverse',
  ]),
  directionMd: PropTypes.oneOf([
    'row',
    'row-reverse',
    'column',
    'column-reverse',
  ]),
  directionLg: PropTypes.oneOf([
    'row',
    'row-reverse',
    'column',
    'column-reverse',
  ]),
  directionXl: PropTypes.oneOf([
    'row',
    'row-reverse',
    'column',
    'column-reverse',
  ]),
  directionXxl: PropTypes.oneOf([
    'row',
    'row-reverse',
    'column',
    'column-reverse',
  ]),
  justifyContent: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'evenly',
  ]),
  justifyContentSm: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'evenly',
  ]),
  justifyContentMd: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'evenly',
  ]),
  justifyContentLg: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'evenly',
  ]),
  justifyContentXl: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'evenly',
  ]),
  justifyContentXxl: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'evenly',
  ]),
  alignItems: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  alignItemsSm: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  alignItemsMd: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  alignItemsLg: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  alignItemsXl: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  alignItemsXxl: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  alignSelf: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  alignSelfSm: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  alignSelfMd: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  alignSelfLg: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  alignSelfXl: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  alignSelfXxl: PropTypes.oneOf([
    'start',
    'end',
    'center',
    'baseline',
    'stretch',
  ]),
  isFill: PropTypes.bool,
  isFillSm: PropTypes.bool,
  isFillMd: PropTypes.bool,
  isFillLg: PropTypes.bool,
  isFillXl: PropTypes.bool,
  isFillXxl: PropTypes.bool,
  flexGrow: PropTypes.oneOf([0, 1]),
  flexGrowSm: PropTypes.oneOf([0, 1]),
  flexGrowMd: PropTypes.oneOf([0, 1]),
  flexGrowLg: PropTypes.oneOf([0, 1]),
  flexGrowXl: PropTypes.oneOf([0, 1]),
  flexGrowXxl: PropTypes.oneOf([0, 1]),
  flexShrink: PropTypes.oneOf([0, 1]),
  flexShrinkSm: PropTypes.oneOf([0, 1]),
  flexShrinkMd: PropTypes.oneOf([0, 1]),
  flexShrinkLg: PropTypes.oneOf([0, 1]),
  flexShrinkXl: PropTypes.oneOf([0, 1]),
  flexShrinkXxl: PropTypes.oneOf([0, 1]),
  isWrap: PropTypes.bool,
  isWrapSm: PropTypes.bool,
  isWrapMd: PropTypes.bool,
  isWrapLg: PropTypes.bool,
  isWrapXl: PropTypes.bool,
  isWrapXxl: PropTypes.bool,
  isNoWrap: PropTypes.bool,
  isNoWrapSm: PropTypes.bool,
  isNoWrapMd: PropTypes.bool,
  isNoWrapLg: PropTypes.bool,
  isNoWrapXl: PropTypes.bool,
  isNoWrapXxl: PropTypes.bool,
  isWrapReverse: PropTypes.bool,
  isWrapReverseSm: PropTypes.bool,
  isWrapReverseMd: PropTypes.bool,
  isWrapReverseLg: PropTypes.bool,
  isWrapReverseXl: PropTypes.bool,
  isWrapReverseXxl: PropTypes.bool,
  order: PropTypes.oneOf([
    1,
    2,
    3,
    4,
    5,
    'first',
    'last',
  ]),
  orderSm: PropTypes.oneOf([
    1,
    2,
    3,
    4,
    5,
    'first',
    'last',
  ]),
  orderMd: PropTypes.oneOf([
    1,
    2,
    3,
    4,
    5,
    'first',
    'last',
  ]),
  orderLg: PropTypes.oneOf([
    1,
    2,
    3,
    4,
    5,
    'first',
    'last',
  ]),
  orderXl: PropTypes.oneOf([
    1,
    2,
    3,
    4,
    5,
    'first',
    'last',
  ]),
  orderXxl: PropTypes.oneOf([
    1,
    2,
    3,
    4,
    5,
    'first',
    'last',
  ]),
  alignContent: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'stretch',
  ]),
  alignContentSm: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'stretch',
  ]),
  alignContentMd: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'stretch',
  ]),
  alignContentLg: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'stretch',
  ]),
  alignContentXl: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'stretch',
  ]),
  alignContentXxl: PropTypes.oneOf([
    'start',
    'end',
    'between',
    'around',
    'stretch',
  ]),
  margin: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  marginSm: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  marginMd: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  marginLg: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  marginXl: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  marginXxl: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  marginX: PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  marginY: PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  mt: PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
  me: PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
  mb: PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
  ms: PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
  padding: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  paddingSm: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  paddingMd: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  paddingLg: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  paddingXl: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  paddingXxl: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
    ),
    PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  ]),
  paddingX: PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  paddingY: PropTypes.oneOf([0, 1, 2, 3, 4, 5]),
  pt: PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
  pe: PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
  pb: PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
  ps: PropTypes.oneOf([0, 1, 2, 3, 4, 5, 'auto']),
  bgColor: PropTypes.oneOf([
    'primary',
    'secondary',
    'success',
    'danger',
    'warning',
    'info',
    'light',
    'dark',
    'body',
    'white',
    'transparent',
  ]),
  textColor: PropTypes.oneOf([
    'primary',
    'secondary',
    'success',
    'danger',
    'warning',
    'info',
    'light',
    'dark',
    'body',
    'muted',
    'white',
    'black-50',
    'white-50',
    'reset',
  ]),
  isBorder: PropTypes.oneOfType([
    PropTypes.bool,
    PropTypes.oneOf([
      'primary',
      'secondary',
      'success',
      'danger',
      'warning',
      'info',
      'light',
      'dark',
      'white',
    ]),
  ]),
};

FlexBox.defaultProps = {
  as: 'div',
  style: null,
  className: null,
  display: 'flex',
  displaySm: null,
  displayMd: null,
  displayLg: null,
  displayXl: null,
  displayXxl: null,
  width: null,
  direction: null,
  directionSm: null,
  directionMd: null,
  directionLg: null,
  directionXl: null,
  directionXxl: null,
  justifyContent: null,
  justifyContentSm: null,
  justifyContentMd: null,
  justifyContentLg: null,
  justifyContentXl: null,
  justifyContentXxl: null,
  alignItems: null,
  alignItemsSm: null,
  alignItemsMd: null,
  alignItemsLg: null,
  alignItemsXl: null,
  alignItemsXxl: null,
  alignSelf: null,
  alignSelfSm: null,
  alignSelfMd: null,
  alignSelfLg: null,
  alignSelfXl: null,
  alignSelfXxl: null,
  isFill: false,
  isFillSm: false,
  isFillMd: false,
  isFillLg: false,
  isFillXl: false,
  isFillXxl: false,
  flexGrow: null,
  flexGrowSm: null,
  flexGrowMd: null,
  flexGrowLg: null,
  flexGrowXl: null,
  flexGrowXxl: null,
  flexShrink: null,
  flexShrinkSm: null,
  flexShrinkMd: null,
  flexShrinkLg: null,
  flexShrinkXl: null,
  flexShrinkXxl: null,
  isWrap: false,
  isWrapSm: false,
  isWrapMd: false,
  isWrapLg: false,
  isWrapXl: false,
  isWrapXxl: false,
  isNoWrap: false,
  isNoWrapSm: false,
  isNoWrapMd: false,
  isNoWrapLg: false,
  isNoWrapXl: false,
  isNoWrapXxl: false,
  isWrapReverse: false,
  isWrapReverseSm: false,
  isWrapReverseMd: false,
  isWrapReverseLg: false,
  isWrapReverseXl: false,
  isWrapReverseXxl: false,
  order: null,
  orderSm: null,
  orderMd: null,
  orderLg: null,
  orderXl: null,
  orderXxl: null,
  alignContent: null,
  alignContentSm: null,
  alignContentMd: null,
  alignContentLg: null,
  alignContentXl: null,
  alignContentXxl: null,
  margin: null,
  marginSm: null,
  marginMd: null,
  marginLg: null,
  marginXl: null,
  marginXxl: null,
  marginX: null,
  marginY: null,
  mt: null,
  me: null,
  mb: null,
  ms: null,
  padding: null,
  paddingSm: null,
  paddingMd: null,
  paddingLg: null,
  paddingXl: null,
  paddingXxl: null,
  paddingX: null,
  paddingY: null,
  pt: null,
  pe: null,
  pb: null,
  ps: null,
  bgColor: null,
  textColor: null,
  isBorder: false,
};

export default FlexBox;
